---
title: "Exploratory Data Analysis"
author: "Your Name"
date: "03/03/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
```

# Load the data
```{r}
intervals <- read.csv("C:/Users/JDS221/GWU/DATS6101/projects/DATS6101_Project/data/fitbit/timestep_data/intervals.csv")
```

# Want to see how different features affect calories burned
```{r}
nrow(intervals)
```

```{r}
summary(intervals$avg_calories)
```

# Plots
```{r}
ggplot(intervals, aes(x = avg_steps, y = avg_calories, color=avg_intensity)) +
  geom_point() +
  ggtitle("Scatterplot of Steps vs. Calories Burned") +
  xlab("Steps") +
  ylab("Calories")

ggplot(intervals, aes(x = avg_steps, y = avg_calories, color=avg_intensity)) +
  geom_point() +
  ggtitle("Scatterplot of Steps vs. Calories Burned") +
  xlab("Steps") +
  ylab("Calories")

ggplot(intervals, aes(x = avg_steps, y = avg_mets, color=avg_intensity)) +
  geom_point() +
  ggtitle("Scatterplot of Steps vs. METs") +
  xlab("Steps") +
  ylab("METs")

ggplot(intervals, aes(y = avg_calories)) +
  geom_boxplot(fill = "green", color = "black") +
  ggtitle("Boxplot of Calories Burned") +
  ylab("Calories Burned")

ggplot(intervals, aes(y = avg_steps)) +
  geom_boxplot(fill = "green", color = "black") +
  ggtitle("Boxplot of Steps Taken") +
  ylab("teps Taken")
```
```{r}
ggplot(intervals, aes(x=day_of_week, y = avg_calories)) +
  geom_boxplot(fill = "green", color = "black") +
  ggtitle("Calories Burned By Day of Week") +
  ylab("Calories Burned")

ggplot(intervals, aes(x=day_of_week, y = avg_steps)) +
  geom_boxplot(fill = "green", color = "black") +
  ggtitle("Steps Taken By Day of Week") +
  ylab("Steps Taken")
```


```{r}
qqnorm(intervals$avg_steps, main = "QQ Steps Taken")
qqline(intervals$avg_steps, col='red')

qqnorm(intervals$avg_calories, main = "QQ Calories Burned")
qqline(intervals$avg_calories, col='red')
```
**Data mostly falls on the line, therefore the data is likely normal**
